name: Run MATLAB Script on GitHub-Hosted Runner
on: push
jobs:      
        
  my-second-job:
    continue-on-error: true
    strategy:
      matrix:
         platform: [ubuntu-latest, ubuntu-18.04]
    name: Run bash command
    runs-on: ${{matrix.platform}}
    steps:
      - name: Initialise
        run: |
          a=2
      - name: Initialize b
        if: matrix.platform == 'ubuntu-latest'
        run: b = 3
        
      - name: sum
        run: c = a+b;
        
  my-third-job:
    continue-on-error: true
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Assign release version from version.properties to Env variable
        run: |
          pwd
          ls
          cd sampleRepo
          cat src/folderA/data.properties >> $GITHUB_ENV  
      
      - name: run ls
        run: echo "${{env.matlab}}"
