name: Set up MATLAB integration test cases
on: [workflow_dispatch]
jobs:
    Build_fails_for_Invalid_command:
      name: Build with Release Option
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v2
        - name: Install MATLAB
          uses: matlab-actions/setup-matlab@v0
          with:
            release: R2020b
        - name: Run MATLAB command
          uses: matlab-actions/run-command@v0
          with:
            command: version
