name: Run MATLAB Script on GitHub-Hosted Runner
on: [push]
jobs:
  my-job:
    name: Run MATLAB Script
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v0
        with:
            release: R2020b
      - name: Run script
        uses: matlab-actions/run-command@v0
        with:
          command: version          
      - name: Run Tests
        uses: matlab-actions/run-tests@v0
        with:
          source-folder: src/folderA
          test-results-pdf: test-results/results.pdf
          test-results-junit: test-results/results.xml
          select-by-tag: TestSquare
      - name: testing artifacts
        run: |
          if(grep -c testSquareForNumbers test-results/results.xml == 0); then
            echo "test failed"
            exit 1
            

  second-job:
    name: second
    runs-on: ubuntu-latest
    steps:
      - run: pwd
# name: Release option
# on: 
#   workflow_dispatch:
#     inputs:
#       releaseOption:
#         description: 'Release Option for build'     
#         required: true
#       runnerName:
#         description: 'Runner used for build'
#         required: true
# jobs:
#     Build_fails_for_Invalid_command:
#       name: Build with Release Option
#       runs-on: ${{ github.event.inputs.runnerName }}
#       steps:
#         - name: Check out repository
#           uses: actions/checkout@v2
#         - name: Install MATLAB
#           uses: matlab-actions/setup-matlab@v0
#           with:
#             release: ${{ github.event.inputs.releaseOption }}
#         - name: Run MATLAB command
#           uses: matlab-actions/run-command@v0
#           with:
#             command: version
