name: Set up MATLAB integration test cases
on: 
 workflow_dispatch:
  inputs:
      release_option:
        description: 'MATLAB release'     
        required: true
jobs:
    Build_fails_for_Invalid_command:
      name: Build with Release Option
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v2
        - name: Install MATLAB
          uses: matlab-actions/setup-matlab@v0
          with:
            release: release_option
        - name: Run MATLAB command
          uses: matlab-actions/run-command@v0
          with:
            command: version
