name: Negative tests
on: [push]
jobs:
  my-job:
    name: Run MATLAB Script
    runs-on: ubuntu-latest
    steps:
      #set up
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v1
      # negative test case
      - name: Run script
        uses: matlab-actions/run-command@v1
        with:
          command: version
