name: Run MATLAB Script on GitHub-Hosted Runner
on: push
jobs:
  my-job-test:
   name: Run MATLAB Script
   runs-on: ubuntu-latest
   steps:
     - name: cli run
       run: |
        gh version
        echo ${{secrets.GH_TOKEN}}
        export GITHUB_TOKEN=${{ secrets.REST_API_TOKEN }}
        echo ${{github.job}}
        echo ${{github.run_id}}
        gh repo clone Vahila/sampleRepo
        cd sampleRepo
        gh run view ${{github.run_id}} --log | grep -c cli
        
