name: Run MATLAB Script on GitHub-Hosted Runner
on: [push]
jobs:
  my-job:
    name: Run MATLAB Script
    runs-on: ubuntu-latest
    steps:
      - name: Assign release version from version.properties to Env variable
        run: pwd
      
      - name: run ls
        run: ls
