name: Read logs
on: push

jobs:
  read-logs:
    name: Reading logs
    runs-on: ubuntu-latest
    steps:
#       - name: Test files running
#         run: curl --request POST --header "Authorization:Bearer ${{ secrets.GITHUB_TOKEN }}" --url "https://api.github.com/repos/Vahila/sampleRepo/actions/workflows/${{matrix.test-files}}/dispatches"       

      - name: API to get logs
        run: |
          curl --request GET --header "Authorization:Bearer ${{ secrets.GITHUB_TOKEN }}" --url "https://api.github.com/repos/octocat/hello-world/actions/workflows/${{matrix.test-files}}/runs" -o runs.json
          ls
          databasename=`cat runs.json | json select '.workflow_runs[0]'`
