name: Run MATLAB Script on GitHub-Hosted Runner
on: [push]
jobs:
  my-job:
    name: Run MATLAB Script
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Assign release version from version.properties to Env variable
        run: |
          pwd
          ls
          cat data.properties >> $GITHUB_ENV  
      
      - name: run ls
        run: echo "${{env.matlab}}"
