name: Run MATLAB Script on GitHub-Hosted Runner
on: [push]
jobs:
  my-job-test:
   name: Run MATLAB Script
   runs-on: ubuntu-latest
   steps:
     - name: cli run
       shell: bash
       run: |
        gh version
        echo ${{secrets.GH_TOKEN}}
        export GITHUB_TOKEN=${{secrets.GH_TOKEN}}
        gh run view --job=2891926639 --log | grep -c test
