name: Run MATLAB Script on GitHub-Hosted Runner
on: push
jobs:
  my-job-test:
   name: Run MATLAB Script
   runs-on: ubuntu-latest
   steps:
     - name: cli run
       run: |
        gh version
        echo ${{secrets.GH_TOKEN}}
        export GITHUB_TOKEN=${{ secrets.CLI_SECRET }}
        gh repo clone Vahila/sampleRepo
        gh run view 982053967 --log
        gh run view --job=2940382877 --log | grep -c test
