name: Run MATLAB Script on GitHub-Hosted Runner
on: [push]
jobs:
  my-job:
    name: Run MATLAB Script
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Run script
        uses: matlab-actions/run-command@v0
        with:
          command: version          
      - name: Run Tests
        uses: matlab-actions/run-tests@newoptions-bash
        with:
          source-folder: src/folderA
          select-by-tag: TestSquare
            
#       - name: Upload artifacts
#         uses: actions/upload-artifact@v2
#         with:
#           name: code-coverage-artifact
#           path: test-results-incorrect-path/
          
#       - name: upload to codecov 
#         uses: codecov/codecov-action@v1 
#         with:
#           file: code-coverage/coverage.xml



