name: Test Runner
on: workflow_dispatch
jobs:
  test-runner:
    strategy:
      matrix:
        test-files: [bashTest.yml, buildWithReleaseOption.yml]
    name: Test Runner
    runs-on: ubuntu-latest
    steps:
      - name: Test files running
        run: curl --request POST -H "Accept:application/vnd.github.v3+json" --header 'authorization:Bearer ${{ secrets.REST_API_TOKEN }}'  --url "https://api.github.com/repos/Vahila/sampleRepo/actions/workflows/${{matrix.test-files}}/dispatches"
         
