name: Integration test cases
on: push
jobs:
    Build_fails_for_Invalid_command:
      strategy:
            matrix:
                platform: [ubuntu-latest, ubuntu-18.04]
      runs-on: ${{ matrix.platform }}
      steps:
        - name: Check out repository
          uses: actions/checkout@v2
        - name: Install MATLAB
          uses: matlab-actions/setup-matlab@v0
          with:
              release: R2020b
        - name: Run command
          uses: matlab-actions/run-command@v0
          with:
            command: version
