name: Integration test cases
on: [push]
jobs:
    Build_fails_for_Invalid_command:
      strategy:
            matrix:
                platform: [ubuntu-latest, macos-latest, windows-latest]
      runs-on: ${{ matrix.platform }}
      steps:
        - name: Check out repository
          uses: actions/checkout@v2
        - name: Install MATLAB
          uses: matlab-actions/setup-matlab@v0
          with:
              release: R2020b
        - name: Run invalid command
          uses: matlab-actions/run-command@v0
          with:
            command: versi
    Build_fails_when_MATLAB_is_not_setup:
        name: Build without MATLAB
        runs-on: ubuntu-latest
        steps:
          - name: Check out repository
            uses: actions/checkout@v2
          - name: Run command 
            uses: matlab-actions/run-command@v0
            with:
              command: version
