name: Build status from different step
on: [push]
jobs:
  job:
    runs-on: ubuntu-latest
    
    steps:       
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v0
        continue-on-error: true
        
      - name: Run the command
        id: run_the_command
        uses: matlab-actions/run-command@v0
          with:
            command: version
            
      - name: Check on failures
        if: job.steps.run_the_command.status == failure()
        run: exit 1
